[workspace]
authors = ["MatteoGuglielmi-Tech <matteo.guglielmi.ma.gu@gmail.com>"]
channels = ["conda-forge"]
name = "src_rust"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
exe = "cargo run"
test = "cargo test"
install = "cargo add"

[dependencies]
