[workspace]
authors = ["MatteoGuglielmi-tech <matteo.guglielmi.ma.gu@gmail.com>"]
channels = ["conda-forge"]
name = "VuLLM"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pandas = ">=2.3.2,<3"
matplotlib = ">=3.10.6,<4"
seaborn = ">=0.13.2,<0.14"
python-dotenv = ">=1.1.1,<2"
scikit-learn = ">=1.7.2,<2"
jsonlines = ">=4.0.0,<5"
graphviz = ">=13.1.2,<14"
plotly = ">=6.3.0,<7"
optuna = ">=4.5.0,<5"
python-telegram-bot = ">=22.5,<23"

[pypi-dependencies]
unsloth = ">=2025.9.7, <2026"
liger-kernel = ">=0.6.2, <0.7"
wandb = ">=0.22.0, <0.23"
weave = ">=0.52.8, <0.53"
kaleido = ">=1.1.0, <2"
tiktoken = ">=0.11.0, <0.12"
openai = ">=2.1.0, <3"
trl = ">=0.22.2, <0.23"
